
return {
	{--------------------- LEVEL 1 : Tutorial
		colors = 2,
		combo = {BLUE,GREEN},
		minDelay = 1500,
		maxDelay = 2500,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 2
		colors = 2,
		combo = {BLUE,GREEN},
		minDelay = 1500,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 3
		colors = 2,
		combo = {BLUE,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 4
		colors = 2,
		combo = {BLUE,GREEN,BLUE,GREEN,BLUE},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 5
		colors = 2,
		combo = {BLUE,BLUE,BLUE,BLUE,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2000,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 6
		colors = 3,
		combo = {BLUE,GREEN,YELLOW,BLUE},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 7
		colors = 3,
		combo = {GREEN,GREEN,YELLOW,BLUE,YELLOW},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 24,
		maxSpeed = 31,
	},
	{--------------------- LEVEL 8
		colors = 3,
		combo = {YELLOW,GREEN,YELLOW,BLUE,YELLOW, YELLOW, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 9
		colors = 3,
		combo = {GREEN,GREEN,BLUE,YELLOW, YELLOW, GREEN, BLUE, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 10
		colors = 3,
		combo = {BLUE,GREEN,BLUE,YELLOW, YELLOW, GREEN, GREEN, YELLOW, BLUE, GREEN, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 11
		colors = 3,
		combo = {GREEN,GREEN, BLUE, YELLOW, YELLOW, BLUE, GREEN, YELLOW, BLUE, GREEN, YELLOW, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 12
		colors = 3,
		combo = {YELLOW, BLUE, GREEN, YELLOW, YELLOW, YELLOW, BLUE, BLUE, BLUE, GREEN, YELLOW, BLUE, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 13
		colors = 3,
		combo = {YELLOW, BLUE, GREEN, GREEN, BLUE, YELLOW, YELLOW, BLUE, GREEN, GREEN, BLUE, YELLOW, YELLOW, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 14
		colors = 4,
		combo = {YELLOW, BLUE, RED, GREEN, BLUE, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 15
		colors = 4,
		combo = {YELLOW, YELLOW, RED, RED, BLUE, BLUE, GREEN, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 16
		colors = 4,
		combo = {RED, RED, BLUE, GREEN, GREEN, YELLOW, YELLOW, RED, BLUE, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 17
		colors = 4,
		combo = {BLUE, RED, BLUE, GREEN, BLUE, YELLOW, BLUE, BLUE, RED, BLUE, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 18
		colors = 4,
		combo = {GREEN, BLUE, RED, BLUE, GREEN, BLUE, YELLOW, BLUE, GREEN, BLUE, RED, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 19
		colors = 4,
		combo = {YELLOW, BLUE, GREEN, BLUE, YELLOW, BLUE, YELLOW, YELLOW ,YELLOW, GREEN, BLUE, GREEN, RED, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 20  (17 asteroids)
		colors = 4,
		combo = {BLUE, BLUE, BLUE, GREEN, GREEN, GREEN, BLUE, YELLOW, BLUE, YELLOW, BLUE ,YELLOW, GREEN, BLUE, GREEN, RED, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 22,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 21 (17 asteroids)
		colors = 4,
		combo = {YELLOW, RED, BLUE, GREEN, GREEN, BLUE, BLUE, YELLOW, YELLOW, BLUE ,YELLOW, GREEN, BLUE, GREEN, YELLOW, RED, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 22,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 22 (18 asteroids)
		colors = 4,
		combo = {GREEN, BLUE, BLUE, YELLOW, YELLOW, BLUE, GREEN, RED, BLUE, YELLOW, RED, BLUE, GREEN, BLUE, GREEN, YELLOW, RED, RED, BLUE},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 22,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 23 (19 asteroids)
		colors = 4,
		combo = {YELLOW, BLUE, GREEN, RED, BLUE, YELLOW, RED, BLUE, GREEN, BLUE, GREEN, YELLOW, RED, RED, BLUE, GREEN, GREEN, GREEN, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 23,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 24 (20 asteroids)
		colors = 4,
		combo = {RED, BLUE, GREEN, BLUE, BLUE, GREEN, YELLOW, YELLOW, RED, RED, BLUE, GREEN, GREEN, YELLOW, GREEN, RED, BLUE, YELLOW, RED, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 23,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 25 (20 asteroids)
		colors = 4,
		combo = {RED, RED, RED, RED, RED, GREEN, YELLOW, YELLOW, RED, RED, BLUE, GREEN, GREEN, YELLOW, BLUE, RED, BLUE, YELLOW, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 23,
		maxSpeed = 27,
	},
	{--------------------- LEVEL 26 (21 asteroids)
		colors = 4,
		combo = {GREEN, RED, BLUE, RED, RED, GREEN, BLUE, YELLOW, YELLOW, RED, BLUE, GREEN, YELLOW, BLUE, RED, BLUE, YELLOW, RED, GREEN, GREEN, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 23,
		maxSpeed = 27,
	},
}
