
return {
	{--------------------- LEVEL 1 : Tutorial
		colors = 2,
		combo = {BLUE,GREEN},
		minDelay = 1500,
		maxDelay = 2500,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 2
		colors = 2,
		combo = {BLUE,GREEN},
		minDelay = 1500,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 3
		colors = 2,
		combo = {BLUE,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 4
		colors = 2,
		combo = {BLUE,GREEN,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 5
		colors = 2,
		combo = {BLUE,GREEN,GREEN,BLUE, GREEN},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 6
		colors = 2,
		combo = {BLUE,BLUE,BLUE,BLUE,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 7
		colors = 2,
		combo = {BLUE,GREEN,BLUE,GREEN,GREEN,BLUE,GREEN},
		minDelay = 2000,
		maxDelay = 2000,
		changeDelaySec = 20,
		changeDelayAmount = 100,
		minSpeed = 15,
		maxSpeed = 20,
	},
	{--------------------- LEVEL 8
		colors = 3,
		combo = {BLUE,GREEN,YELLOW,BLUE},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 9
		colors = 3,
		combo = {GREEN,GREEN,YELLOW,BLUE,YELLOW},
		minDelay = 2000,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 24,
		maxSpeed = 31,
	},
	{--------------------- LEVEL 10
		colors = 3,
		combo = {YELLOW,GREEN,YELLOW,BLUE,YELLOW, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 11
		colors = 3,
		combo = {GREEN,YELLOW,BLUE,YELLOW, YELLOW, GREEN, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 12 (8 colors)
		colors = 3,
		combo = {BLUE,YELLOW, GREEN, GREEN, YELLOW, BLUE, GREEN, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 13 (9 colors)
		colors = 3,
		combo = {GREEN,GREEN,BLUE,YELLOW, YELLOW, GREEN, BLUE, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 17,
		maxSpeed = 22,
	},
	{--------------------- LEVEL 14 (11 colors)
		colors = 3,
		combo = {BLUE,GREEN,BLUE,YELLOW, YELLOW, GREEN, GREEN, YELLOW, BLUE, GREEN, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 15 (13 colors)
		colors = 3,
		combo = {GREEN,GREEN, BLUE, YELLOW, YELLOW, BLUE, GREEN, YELLOW, BLUE, GREEN, YELLOW, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 16 (14 colors)
		colors = 3,
		combo = {YELLOW, BLUE, GREEN, YELLOW, YELLOW, YELLOW, BLUE, BLUE, BLUE, GREEN, YELLOW, BLUE, BLUE, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 19,
		maxSpeed = 23,
	},
	{--------------------- LEVEL 17 (14 colors)
		colors = 3,
		combo = {YELLOW, BLUE, GREEN, GREEN, BLUE, YELLOW, YELLOW, BLUE, GREEN, GREEN, BLUE, YELLOW, YELLOW, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 18 (9 colors)
		colors = 4,
		combo = {GREEN, BLUE, YELLOW, YELLOW, BLUE, RED, GREEN, BLUE, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 19 (9 colors)
		colors = 4,
		combo = {YELLOW, YELLOW, RED, RED, BLUE, BLUE, GREEN, GREEN, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 20 (10 colors)
		colors = 4,
		combo = {RED, RED, BLUE, GREEN, GREEN, YELLOW, YELLOW, RED, BLUE, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 20,
		changeDelayAmount = 150,
		minSpeed = 20,
		maxSpeed = 24,
	},
	{--------------------- LEVEL 21
		colors = 4,
		combo = {BLUE, RED, BLUE, GREEN, BLUE, YELLOW, BLUE, BLUE, RED, BLUE, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 22
		colors = 4,
		combo = {GREEN, BLUE, RED, BLUE, GREEN, BLUE, YELLOW, BLUE, GREEN, BLUE, RED, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 23
		colors = 4,
		combo = {YELLOW, BLUE, GREEN, BLUE, YELLOW, BLUE, YELLOW, YELLOW ,YELLOW, GREEN, BLUE, GREEN, RED, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 21,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 24  (17 asteroids)
		colors = 4,
		combo = {BLUE, BLUE, BLUE, GREEN, GREEN, GREEN, BLUE, YELLOW, BLUE, YELLOW, BLUE ,YELLOW, GREEN, BLUE, GREEN, RED, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 22,
		maxSpeed = 25,
	},
	{--------------------- LEVEL 25 (17 asteroids)
		colors = 4,
		combo = {YELLOW, RED, BLUE, GREEN, GREEN, BLUE, BLUE, YELLOW, YELLOW, BLUE ,YELLOW, GREEN, BLUE, GREEN, YELLOW, RED, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 22,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 26 (18 asteroids)
		colors = 4,
		combo = {GREEN, BLUE, BLUE, YELLOW, YELLOW, BLUE, GREEN, RED, BLUE, YELLOW, RED, BLUE, GREEN, BLUE, GREEN, YELLOW, RED, RED, BLUE},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 22,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 27 (19 asteroids)
		colors = 4,
		combo = {YELLOW, BLUE, GREEN, RED, BLUE, YELLOW, RED, BLUE, GREEN, BLUE, GREEN, YELLOW, RED, RED, BLUE, GREEN, GREEN, GREEN, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 23,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 28 (20 asteroids)
		colors = 4,
		combo = {RED, BLUE, GREEN, BLUE, BLUE, GREEN, YELLOW, YELLOW, RED, RED, BLUE, GREEN, GREEN, YELLOW, GREEN, RED, BLUE, YELLOW, RED, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 23,
		maxSpeed = 26,
	},
	{--------------------- LEVEL 29 (20 asteroids)
		colors = 4,
		combo = {RED, RED, RED, RED, RED, GREEN, YELLOW, YELLOW, RED, RED, BLUE, GREEN, GREEN, YELLOW, BLUE, RED, BLUE, YELLOW, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 23,
		maxSpeed = 27,
	},
	{--------------------- LEVEL 30 (25 asteroids)
		colors = 4,
		combo = {GREEN, RED, BLUE, RED, RED, GREEN, BLUE, YELLOW, YELLOW, RED, BLUE, GREEN, YELLOW, BLUE, RED, BLUE, YELLOW, RED, GREEN, GREEN, RED, YELLOW, GREEN, BLUE, BLUE},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 18,
		changeDelayAmount = 160,
		minSpeed = 23,
		maxSpeed = 27,
	},
	{--------------------- LEVEL 31 (27 asteroids)
		colors = 4,
		combo = {RED, RED, BLUE, RED, RED, GREEN, GREEN, YELLOW, YELLOW, RED, BLUE, BLUE, YELLOW, BLUE, RED, RED, YELLOW, RED, GREEN, GREEN, RED, YELLOW, GREEN, BLUE, YELLOW, RED, BLUE},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 32 (29 asteroids)
		colors = 4,
		combo = {RED, YELLOW, BLUE, RED, GREEN, GREEN, GREEN, YELLOW, BLUE, GREEN, RED, BLUE, BLUE, BLUE, BLUE, RED, RED, YELLOW, RED, YELLOW, GREEN, RED, YELLOW, GREEN, BLUE, YELLOW, RED, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 33 (31 asteroids)
		colors = 4,
		combo = {YELLOW, BLUE, RED, GREEN, YELLOW, GREEN, YELLOW, BLUE, RED, RED,
					BLUE, BLUE, YELLOW, BLUE, RED, GREEN, YELLOW, RED, YELLOW, GREEN,
					RED, YELLOW, GREEN, BLUE, RED, RED, GREEN, RED, BLUE, BLUE, 
					YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 34 (33 asteroids)
		colors = 4,
		combo = {RED, GREEN, RED, GREEN, YELLOW, GREEN, YELLOW, BLUE, YELLOW, RED,
					BLUE, YELLOW, GREEN, BLUE, YELLOW, GREEN, YELLOW, RED, YELLOW, GREEN,
					RED, GREEN, GREEN, BLUE, RED, RED, GREEN, RED, BLUE, BLUE, 
					YELLOW, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 35 (35 asteroids)
		colors = 4,
		combo = {YELLOW, GREEN, RED, GREEN, YELLOW, GREEN, YELLOW, BLUE, YELLOW, RED,
					BLUE, YELLOW, BLUE, BLUE, YELLOW, GREEN, BLUE, RED, YELLOW, GREEN,
					RED, GREEN, GREEN, BLUE, YELLOW, YELLOW, YELLOW, RED, BLUE, BLUE, 
					YELLOW, BLUE, GREEN, BLUE, BLUE},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 36 (37 asteroids)
		colors = 4,
		combo = {BLUE, GREEN, RED, RED, GREEN, GREEN, RED, BLUE, GREEN, RED,
					GREEN, YELLOW, BLUE, GREEN, GREEN, GREEN, BLUE, GREEN, YELLOW, GREEN,
					GREEN, GREEN, GREEN, BLUE, YELLOW, YELLOW, YELLOW, RED, BLUE, BLUE, 
					YELLOW, BLUE, GREEN, RED, BLUE, YELLOW, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 24,
		maxSpeed = 28,
	},
	{--------------------- LEVEL 37 (39 asteroids)
		colors = 4,
		combo = {BLUE, BLUE, RED, BLUE, GREEN, BLUE, RED, BLUE, YELLOW, BLUE,
					GREEN, YELLOW, BLUE, GREEN, YELLOW, GREEN, BLUE, BLUE, YELLOW, GREEN,
					RED, GREEN, RED, BLUE, YELLOW, YELLOW, YELLOW, RED, BLUE, BLUE, 
					YELLOW, BLUE, RED, YELLOW, BLUE, YELLOW, GREEN, YELLOW, RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 15,
		changeDelayAmount = 200,
		minSpeed = 25,
		maxSpeed = 29,
	},
	{--------------------- LEVEL 38 (41 asteroids)
		colors = 4,
		combo = {YELLOW, YELLOW, RED, BLUE, GREEN, BLUE, RED, BLUE, RED, BLUE,
					GREEN, YELLOW, BLUE, GREEN, RED, GREEN, BLUE, BLUE, YELLOW, GREEN,
					RED, GREEN, RED, BLUE, YELLOW, BLUE, YELLOW, BLUE, BLUE, BLUE, 
					YELLOW, BLUE, RED, YELLOW, BLUE, YELLOW, YELLOW, YELLOW, RED, BLUE,
					RED},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 13,
		changeDelayAmount = 220,
		minSpeed = 25,
		maxSpeed = 29,
	},
	{--------------------- LEVEL 39 (43 asteroids)
		colors = 4,
		combo = {YELLOW, BLUE, RED, BLUE, GREEN, BLUE, RED, BLUE, RED, BLUE,
					RED, YELLOW, BLUE, GREEN, RED, GREEN, BLUE, BLUE, YELLOW, GREEN,
					RED, GREEN, RED, BLUE, RED, BLUE, YELLOW, GREEN, RED, BLUE, 
					YELLOW, BLUE, RED, YELLOW, BLUE, YELLOW, RED, YELLOW, GREEN, BLUE,
					RED, RED, GREEN},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 13,
		changeDelayAmount = 220,
		minSpeed = 25,
		maxSpeed = 29,
	},
	{--------------------- LEVEL 40 (45 asteroids)
		colors = 4,
		combo = {GREEN, BLUE, BLUE, BLUE, YELLOW, BLUE, RED, BLUE, RED, YELLOW,
					GREEN, GREEN, BLUE, GREEN, YELLOW, GREEN, YELLOW, BLUE, YELLOW, GREEN,
					RED, GREEN, RED, BLUE, RED, BLUE, GREEN, GREEN, RED, BLUE, 
					YELLOW, YELLOW, RED, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, GREEN, BLUE,
					RED, RED, GREEN, YELLOW, YELLOW},
		minDelay = 1800,
		maxDelay = 2500,
		changeDelaySec = 10,
		changeDelayAmount = 220,
		minSpeed = 26,
		maxSpeed = 30,
	},
}
